---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 512

provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
  - recipe[ktc-testing]
  - recipe[ktc-etcd]
  - recipe[ktc-sensu::master]
  - recipe[collectd::client]
  - recipe[ktc-base]
  attributes: 
    authorization:
      sudo:
        users:
          - ubuntu
          - vagrant
        passwordless: true
    etcd:
      args: -c 127.0.0.1:4001 -s 127.0.0.1:7001
      servers:
        - 127.0.0.1
    ha_disabled: true
    omnibus_updater:
      disabled: true
    tz: GMT

clusters:
  default:
    - default
